import { prisma } from "@/lib/prisma";
import { CalendarEventType, ReminderChannel } from "@/generated/prisma/client";

// ─── AUTO EVENT CREATION ────────────────────────────────────

interface TenderInfo {
  id: string;
  title: string;
  deadline: Date;
  openingDate?: Date | null;
  institution: string;
}

export async function onFavoriteAdded(userId: string, tender: TenderInfo) {
  const events = [];

  // 1. Son başvuru tarihi (7, 3, 1 gün önce hatırlatma)
  events.push({
    userId,
    tenderId: tender.id,
    title: `Son Başvuru: ${tender.title}`,
    description: `${tender.institution} - Son başvuru tarihi`,
    eventType: "SON_BASVURU" as CalendarEventType,
    startDate: tender.deadline,
    reminderDays: [7, 3, 1],
    isAutoGenerated: true,
  });

  // 2. Soru sorma son tarihi (genellikle 10 gün önce)
  const questionDate = new Date(tender.deadline);
  questionDate.setDate(questionDate.getDate() - 10);
  if (questionDate > new Date()) {
    events.push({
      userId,
      tenderId: tender.id,
      title: `Soru Sorma Son Tarihi: ${tender.title}`,
      description: `${tender.institution} - İhaleye ilişkin soruların sorulabileceği son tarih`,
      eventType: "SORU_TARIHI" as CalendarEventType,
      startDate: questionDate,
      reminderDays: [3],
      isAutoGenerated: true,
    });
  }

  // 3. İhale açıklama tarihi (genellikle deadline + 7 gün)
  if (tender.openingDate) {
    events.push({
      userId,
      tenderId: tender.id,
      title: `İhale Açıklaması: ${tender.title}`,
      description: `${tender.institution} - Tekliflerin açıklanma tarihi`,
      eventType: "ACIKLAMA" as CalendarEventType,
      startDate: tender.openingDate,
      reminderDays: [1],
      isAutoGenerated: true,
    });
  }

  // Create events
  const created = [];
  for (const evt of events) {
    // Skip duplicates
    const exists = await prisma.calendarEvent.findFirst({
      where: {
        userId,
        tenderId: tender.id,
        eventType: evt.eventType,
      },
    });
    if (exists) continue;

    const event = await prisma.calendarEvent.create({ data: evt });
    created.push(event);

    // Create smart reminders
    for (const days of evt.reminderDays) {
      const scheduledAt = new Date(evt.startDate);
      scheduledAt.setDate(scheduledAt.getDate() - days);
      if (scheduledAt > new Date()) {
        await prisma.smartReminder.create({
          data: {
            userId,
            eventId: event.id,
            message: generateSmartReminderMessage(evt.title, days, evt.eventType),
            scheduledAt,
            channel: "IN_APP",
            aiGenerated: true,
          },
        });
      }
    }
  }

  return created;
}

// ─── SMART REMINDER ─────────────────────────────────────────

function generateSmartReminderMessage(
  title: string,
  daysLeft: number,
  eventType: CalendarEventType,
): string {
  const dayStr = daysLeft === 1 ? "1 gün" : `${daysLeft} gün`;

  switch (eventType) {
    case "SON_BASVURU":
      if (daysLeft <= 1) return `⚠️ ${title} — YARIN son başvuru günü! Teklifinizi tamamlayın.`;
      if (daysLeft <= 3) return `🔴 ${title} — Son başvuruya ${dayStr} kaldı. Teklif hazırlığınızı kontrol edin.`;
      return `📋 ${title} — Son başvuruya ${dayStr} kaldı. Belge eksikliği var mı kontrol edin.`;
    case "SORU_TARIHI":
      return `❓ ${title} — Soru sorma tarihine ${dayStr} kaldı. Teknik şartnameyi inceleyin.`;
    case "ACIKLAMA":
      return `📢 ${title} — İhale açıklamasına ${dayStr} kaldı.`;
    case "ZEYILNAME":
      return `📝 ${title} — Zeyilname bildirim tarihi. Değişiklikleri kontrol edin.`;
    default:
      return `📌 ${title} — ${dayStr} kaldı.`;
  }
}

// ─── CONFLICT DETECTION ─────────────────────────────────────

export interface ConflictGroup {
  date: string;
  events: {
    id: string;
    title: string;
    tenderId: string | null;
    eventType: string;
    startDate: string;
  }[];
}

export async function detectConflicts(userId: string): Promise<ConflictGroup[]> {
  const events = await prisma.calendarEvent.findMany({
    where: {
      userId,
      eventType: "SON_BASVURU",
      startDate: { gte: new Date() },
    },
    orderBy: { startDate: "asc" },
  });

  // Group by date
  const byDate: Record<string, typeof events> = {};
  for (const evt of events) {
    const dateKey = evt.startDate.toISOString().split("T")[0];
    if (!byDate[dateKey]) byDate[dateKey] = [];
    byDate[dateKey].push(evt);
  }

  // Only return dates with 2+ events
  return Object.entries(byDate)
    .filter(([, evts]) => evts.length >= 2)
    .map(([date, evts]) => ({
      date,
      events: evts.map((e) => ({
        id: e.id,
        title: e.title,
        tenderId: e.tenderId,
        eventType: e.eventType,
        startDate: e.startDate.toISOString(),
      })),
    }));
}

// ─── QUERIES ────────────────────────────────────────────────

export async function getCalendarEvents(userId: string, from?: string, to?: string) {
  const where: Record<string, unknown> = { userId };
  if (from || to) {
    where.startDate = {};
    if (from) (where.startDate as Record<string, unknown>).gte = new Date(from);
    if (to) (where.startDate as Record<string, unknown>).lte = new Date(to);
  }

  return prisma.calendarEvent.findMany({
    where,
    include: { tender: { select: { id: true, title: true, institution: true, deadline: true } } },
    orderBy: { startDate: "asc" },
  });
}

export async function createEvent(data: {
  userId: string;
  tenderId?: string;
  title: string;
  description?: string;
  eventType: CalendarEventType;
  startDate: Date;
  endDate?: Date;
  reminderDays?: number[];
}) {
  return prisma.calendarEvent.create({
    data: {
      userId: data.userId,
      tenderId: data.tenderId || null,
      title: data.title,
      description: data.description || null,
      eventType: data.eventType,
      startDate: data.startDate,
      endDate: data.endDate || null,
      reminderDays: data.reminderDays || [],
      isAutoGenerated: false,
    },
  });
}

export async function updateEvent(id: string, userId: string, data: {
  title?: string;
  description?: string;
  startDate?: Date;
  endDate?: Date;
  reminderDays?: number[];
}) {
  return prisma.calendarEvent.updateMany({
    where: { id, userId },
    data,
  });
}

export async function deleteEvent(id: string, userId: string) {
  return prisma.calendarEvent.deleteMany({
    where: { id, userId },
  });
}

// ─── DAILY SUMMARY ──────────────────────────────────────────

export async function getDailySummary(userId: string) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  const weekEnd = new Date(today);
  weekEnd.setDate(weekEnd.getDate() + 7);

  const [todayEvents, weekEvents, pendingReminders] = await Promise.all([
    prisma.calendarEvent.findMany({
      where: { userId, startDate: { gte: today, lt: tomorrow } },
      orderBy: { startDate: "asc" },
    }),
    prisma.calendarEvent.findMany({
      where: { userId, startDate: { gte: tomorrow, lt: weekEnd } },
      orderBy: { startDate: "asc" },
    }),
    prisma.smartReminder.findMany({
      where: { userId, scheduledAt: { lte: new Date() }, sentAt: null },
      include: { event: true },
      orderBy: { scheduledAt: "asc" },
      take: 10,
    }),
  ]);

  return { todayEvents, weekEvents, pendingReminders };
}

// ─── UPCOMING REMINDERS ─────────────────────────────────────

export async function getUpcomingReminders(userId: string, days: number = 7) {
  const end = new Date();
  end.setDate(end.getDate() + days);

  return prisma.smartReminder.findMany({
    where: {
      userId,
      scheduledAt: { gte: new Date(), lte: end },
    },
    include: { event: true },
    orderBy: { scheduledAt: "asc" },
    take: 20,
  });
}

// ─── SYNC STATUS ────────────────────────────────────────────

export async function getSyncStatus(userId: string) {
  return prisma.calendarSync.findMany({
    where: { userId },
  });
}

export async function upsertSync(userId: string, provider: "GOOGLE" | "OUTLOOK", data: {
  accessToken?: string;
  refreshToken?: string;
  syncEnabled?: boolean;
}) {
  return prisma.calendarSync.upsert({
    where: { userId_provider: { userId, provider } },
    create: { userId, provider, ...data },
    update: data,
  });
}

// ─── ICS EXPORT ─────────────────────────────────────────────

export async function exportToIcs(userId: string) {
  const events = await prisma.calendarEvent.findMany({
    where: { userId, startDate: { gte: new Date() } },
    orderBy: { startDate: "asc" },
  });
  return events;
}

// ─── CONSTANTS ──────────────────────────────────────────────

export const EVENT_TYPE_CONFIG: Record<string, { label: string; color: string; bgColor: string }> = {
  SON_BASVURU: { label: "Son Başvuru", color: "#ef4444", bgColor: "#fef2f2" },
  SORU_TARIHI: { label: "Soru Tarihi", color: "#3b82f6", bgColor: "#eff6ff" },
  ACIKLAMA: { label: "Açıklama", color: "#22c55e", bgColor: "#f0fdf4" },
  ZEYILNAME: { label: "Zeyilname", color: "#f59e0b", bgColor: "#fffbeb" },
  OZEL: { label: "Özel", color: "#8b5cf6", bgColor: "#f5f3ff" },
};

export const CHANNEL_LABELS: Record<string, string> = {
  PUSH: "Push Bildirim",
  EMAIL: "E-posta",
  IN_APP: "Uygulama İçi",
};
